package com.spring.springproject.controller;


public class Constants {
    public static final String TYPES_URL = "/types";
    public static final String TYPE = "/type";
    public static final String DEL_TYPE = "/delType";
    public static final String NEW_TYPE = "/newType";
    public static final String START_PRICE = "startPrice";
    public static final String END_PRICE = "endPrice";
    public static final String TECHNIQUE_BY_PRICE = "/technique-by-price";
    public static final String NEW_TECHNIQUE = "/newTechnique";
    public static final String DEL_TECHNIQUE = "/delTechnique";
    public static final String TECHNIQUE = "/technique";
    public static final String TECHNIQUES = "/techniques";
    public static final String NEW_STORE = "/newStore";
    public static final String DEL_STORE = "/delStore";
    public static final String STORE = "/store";
    public static final String STORES_URL = "/stores";
    public static final String PRODUCERS_URL = "/producers";
    public static final String PRODUCER_URL = "/producer";
    public static final String DEL_PRODUCER = "/delProducer";
    public static final String NEW_PRODUCER = "/newProducer";
    public static final String MODELS_URL = "/models";
    public static final String MODEL_URL = "/model";
    public static final String DEL_MODEL = "/delModel";
    public static final String NEW_MODEL = "/newModel";
    public static final String CATEGORIES_URL = "/categories";
    public static final String CATEGORY_URL = "/category";
    public static final String DEL_CATEGORY = "/delCategory";
    public static final String NEW_CATEGORY = "/newCategory";

    public static final String TYPE_BY_NAME = "/typeByName";
    public static final String MODEL_BY_NAME = "/modelByName";
    public static final String PRODUCER_BY_NAME = "/producerByName";
    public static final String PRODUCER_BY_COUNTRY = "/producerByCountry";
    public static final String STORE_BY_ADDRESS = "/storeByAddress";
    public static final String STORE_BY_NAME = "/storeByName";
    public static final String CATEGORY_BY_NAME = "/categoryByName";
    public static final String LOGIN = "/login";
    public static final String ADMIN = "ADMIN";
    public static final String USER = "USER";
    public static final String CONFIG_MATCHER = "/*";
    public static final String CATEGORY_LIST = "category/catList";
    public static final String LIST = "list";
    public static final String TYPE_ID = "typeId";
    public static final String NAME = "name";
    public static final String CAT_ADD = "/category/catAdd";
    public static final String TYPES = "types";
    public static final String CAT_ID = "catId";

    public static final String CAT_EDIT = "category/catEdit";
    public static final String UNIT = "unit";
    public static final String LIST_NAME = "listName";
    public static final String HOME_VIEW = "/homeView";
    public static final String HOME_PAGE = "homePage";
    public static final String HOME = "/home";
    public static final String START_PAGE = "/";
    public static final String MODEL_MODEL_ADD = "/model/modelAdd";
    public static final String MODEL_ID = "modelId";

    public static final String MOD_EDIT = "model/modelEdit";
    public static final String MOD_LIST = "model/modelList";

    public static final String COUNTRY = "country";
    public static final String PROD_ADD = "/producer/producerAdd";
    public static final String PRODUCER_ID = "producerId";
    public static final String PROD_EDIT = "producer/producerEdit";
    public static final String PROD_LIST = "producer/producerList";
    public static final String ADDRESS = "address";
    public static final String ST_ADD = "/store/storeAdd";
    public static final String STORE_ID = "storeId";
    public static final String ST_EDIT = "store/storeEdit";
    public static final String ST_LIST = "store/storeList";
    public static final String STORES = "stores";
    public static final String PRODUCERS = "producers";
    public static final String MODELS = "models";
    public static final String CATEGORIES = "categories";
    public static final String T_ADD = "tech/techAdd";
    public static final String TECH_ID = "techId";
    public static final String PRICE = "price";
    public static final String CATEGORY = "category";
    public static final String MODEL = "model";
    public static final String PRODUCER = "producer";
    public static final String T_EDIT = "tech/techEdit";
    public static final String T_LIST = "tech/techList";
    public static final String TY_ADD = "/type/typeAdd";
    public static final String TY_EDIT = "type/typeEdit";
    public static final String TY_LIST = "type/typeList";
}
