spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/gov_services?CreateIfNotExists=true
spring.datasource.username=postgres
spring.datasource.password=postgres
server.port=8080
spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
app.image.bucket= D:\\springproject\\src\\main\\img
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Конфигурация загрузки файлов
app.upload.dir=./uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true

# Разрешенные типы файлов
app.upload.allowed-types=application/pdf,image/jpeg,image/png,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document

spring.messages.basename=messages
spring.messages.encoding=UTF-8